import { useState } from "react";
import { reportDataByRange } from "../../data/reportsData";
import "./Reports.css";
import jsPDF from "jspdf";

function Reports() {
    const [range, setRange] = useState("Last 30 Days");
    const [generated, setGenerated] = useState(false);

    const data = reportDataByRange[range];

    const handleGenerateReport = () => {
        setGenerated(true);

        setTimeout(() => {
            setGenerated(false);
        }, 2000);
    };

    const handlePrint = () => {
        window.print();
    };

    const handleDownload = () => {
        const doc = new jsPDF();

        const pageWidth = doc.internal.pageSize.getWidth();
        const margin = 20;

        let y = 20;

        // Title
        doc.setFontSize(20);
        doc.setFont("helvetica", "bold");
        doc.text("Project Loop", margin, y);

        y += 10;

        doc.setFontSize(16);
        doc.text("Feedback Reports", margin, y);

        y += 8;

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 116, 139);
        doc.text(`Report Period: ${range}`, margin, y);

        y += 15;

        // Summary
        doc.setTextColor(15, 23, 42);
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.text("Summary", margin, y);

        y += 9;

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");

        doc.text(`Total Feedback: ${data.totalFeedback}`, margin, y);
        y += 7;

        doc.text(`Overall Sentiment: ${data.overallSentiment}`, margin, y);
        y += 7;

        doc.text(`Resolved: ${data.resolved}`, margin, y);
        y += 7;

        doc.text(`Resolution Rate: ${data.resolutionRate}%`, margin, y);
        y += 7;

        doc.text(`AI Confidence: ${data.aiConfidence}`, margin, y);

        y += 15;

        // Sentiment
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.text("Sentiment Summary", margin, y);

        y += 9;

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");

        doc.text(`Positive: ${data.positive}%`, margin, y);
        y += 7;

        doc.text(`Negative: ${data.negative}%`, margin, y);
        y += 7;

        doc.text(`Neutral: ${data.neutral}%`, margin, y);

        y += 15;

        // Resolution
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.text("Feedback Resolution", margin, y);

        y += 9;

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");

        doc.text(`Resolved: ${data.resolved}`, margin, y);
        y += 7;

        doc.text(`Pending: ${data.pending}`, margin, y);
        y += 7;

        doc.text(`Reviewed: ${data.reviewed}`, margin, y);

        y += 15;

        // Executive AI Summary
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.text("Executive AI Summary", margin, y);

        y += 9;

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");

        data.summary.forEach((item) => {
            const lines = doc.splitTextToSize(
                `• ${item}`,
                pageWidth - margin * 2
            );

            doc.text(lines, margin, y);
            y += lines.length * 6 + 3;
        });

        y += 8;

        // Recommendations
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.text("Priority Recommendations", margin, y);

        y += 9;

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");

        data.recommendations.forEach((recommendation) => {
            const title = `${recommendation.priority}. ${recommendation.title}`;

            doc.setFont("helvetica", "bold");
            doc.text(title, margin, y);

            y += 6;

            doc.setFont("helvetica", "normal");

            const descriptionLines = doc.splitTextToSize(
                recommendation.description,
                pageWidth - margin * 2
            );

            doc.text(descriptionLines, margin, y);

            y += descriptionLines.length * 6 + 6;

            // Create new page if needed
            if (y > 270) {
                doc.addPage();
                y = 20;
            }
        });

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        doc.text(
            "Generated by Project Loop",
            margin,
            285
        );

        // Download PDF
        doc.save(
            `Project-Loop-${range.replaceAll(" ", "-")}-Report.pdf`
        );
    };



    return (
        <div className="reports-page print-report">

            {/* Header */}
            <div className="reports-header">

                <div>
                    <h1>Feedback Reports</h1>

                    <p>
                        Turn customer feedback into clear business decisions.
                    </p>
                </div>

                <div className="reports-actions">

                    <select
                        value={range}
                        onChange={(e) => setRange(e.target.value)}
                    >
                        <option>Last 7 Days</option>
                        <option>Last 30 Days</option>
                        <option>Last 90 Days</option>
                        <option>This Year</option>
                    </select>

                    <button
                        className="generate-btn"
                        onClick={handleGenerateReport}
                    >
                        {generated ? "✓ Report Generated" : "✦ Generate Report"}
                    </button>

                </div>

            </div>


            {/* Summary Cards */}
            <div className="report-stats">

                <div className="report-stat">
                    <span className="report-stat-icon">📊</span>

                    <div>
                        <span>Total Feedback</span>
                        <strong>{data.totalFeedback}</strong>
                        <small>{data.totalFeedbackChange}</small>
                    </div>
                </div>


                <div className="report-stat">
                    <span className="report-stat-icon">😊</span>

                    <div>
                        <span>Overall Sentiment</span>
                        <strong>{data.overallSentiment}</strong>
                        <small>{data.overallSentimentText}</small>
                    </div>
                </div>


                <div className="report-stat">
                    <span className="report-stat-icon">✓</span>

                    <div>
                        <span>Resolved</span>
                        <strong>{data.resolved}</strong>
                        <small>{data.resolutionRate}% resolution rate</small>
                    </div>
                </div>


                <div className="report-stat">
                    <span className="report-stat-icon">✦</span>

                    <div>
                        <span>AI Confidence</span>
                        <strong>{data.aiConfidence}</strong>
                        <small>{data.aiConfidenceText}</small>
                    </div>
                </div>

            </div>


            {/* Main Report */}
            <div className="report-grid">

                {/* Sentiment */}
                <div className="report-card">

                    <div className="report-card-header">
                        <div>
                            <h2>Sentiment Summary</h2>
                            <p>Overall customer sentiment</p>
                        </div>
                    </div>

                    <div className="sentiment-summary">

                        <div className="sentiment-row">
                            <div>
                                <span className="dot positive-dot" />
                                Positive
                            </div>

                            <strong>{data.positive}%</strong>
                        </div>

                        <div className="progress">
                            <div
                                className="progress-positive"
                                style={{ width: `${data.positive}%` }}
                            />
                        </div>


                        <div className="sentiment-row">
                            <div>
                                <span className="dot negative-dot" />
                                Negative
                            </div>

                            <strong>{data.negative}%</strong>
                        </div>

                        <div className="progress">
                            <div
                                className="progress-negative"
                                style={{ width: `${data.negative}%` }}
                            />
                        </div>


                        <div className="sentiment-row">
                            <div>
                                <span className="dot neutral-dot" />
                                Neutral
                            </div>

                            <strong>{data.neutral}%</strong>
                        </div>

                        <div className="progress">
                            <div
                                className="progress-neutral"
                                style={{ width: `${data.neutral}%` }}
                            />
                        </div>

                    </div>

                </div>


                {/* Resolution */}
                <div className="report-card">

                    <div className="report-card-header">
                        <div>
                            <h2>Feedback Resolution</h2>
                            <p>Current feedback status</p>
                        </div>
                    </div>

                    <div className="resolution-rate">

                        <div className="resolution-circle">
                            <strong>{data.resolutionRate}%</strong>
                            <span>Resolved</span>
                        </div>

                        <div className="resolution-details">

                            <div>
                                <span className="status-dot approved" />
                                Resolved
                                <strong>{data.resolved}</strong>
                            </div>

                            <div>
                                <span className="status-dot pending" />
                                Pending
                                <strong>{data.pending}</strong>
                            </div>

                            <div>
                                <span className="status-dot reviewed" />
                                Reviewed
                                <strong>{data.reviewed}</strong>
                            </div>

                        </div>

                    </div>

                </div>

            </div>


            {/* AI Executive Summary */}
            <div className="report-card executive-card">

                <div className="report-card-header">

                    <div>
                        <h2>Executive AI Summary</h2>

                        <p>
                            Key findings generated from analyzed customer feedback.
                        </p>
                    </div>

                    <span className="ai-badge">
                        ✦ AI Insights
                    </span>

                </div>


                <div className="executive-insights">

                    {data.insights.map((insight, index) => (
                        <div className="executive-item" key={index}>

                            <span>{insight.icon}</span>

                            <p>
                                {insight.text}
                                <strong>{insight.value}</strong>
                                {insight.suffix}
                            </p>

                        </div>
                    ))}

                </div>

            </div>


            {/* Recommendations */}
            <div className="report-card">

                <div className="report-card-header">

                    <div>
                        <h2>Priority Recommendations</h2>

                        <p>
                            AI-generated actions based on feedback patterns.
                        </p>
                    </div>

                </div>


                <div className="recommendations">

                    {data.recommendations.map((recommendation, index) => (
                        <div
                            className={`recommendation ${recommendation.className}`}
                            key={index}
                        >

                            <span className="priority-badge">
                                {recommendation.priority}
                            </span>

                            <div>
                                <strong>{recommendation.title}</strong>

                                <p>
                                    {recommendation.description}
                                </p>
                            </div>

                        </div>
                    ))}

                </div>

            </div>


            {/* Footer Actions */}
            <div className="report-footer-actions">

                <button
                    className="secondary-report-btn"
                    onClick={handlePrint}
                >
                    🖨 Print Report
                </button>

                <button
                    className="primary-report-btn"
                    onClick={handleDownload}
                >
                    ↓ Download Report
                </button>

            </div>

        </div>
    );
}

export default Reports;